inherit_from:
  - .rubocop_standard.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-performance

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.2.2
  NewCops: enable

### Cops ###

Bundler/GemFilename:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true

Gemspec/OrderedDependencies:
  Enabled: true

Gemspec/RubyVersionGlobalsUsage:
  Enabled: true

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_block

Layout/BlockEndNewline:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true
  AllowAdjacentOneLineDefs: true

Layout/EmptyLinesAroundArguments:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstArrayElementLineBreak:
  Enabled: true
  AllowMultilineFinalElement: true

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstHashElementLineBreak:
  Enabled: true
  AllowMultilineFinalElement: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true
  AllowMultilineFinalElement: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/FirstParameterIndentation:
  Enabled: true

Layout/HashAlignment:
  Enabled: true
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/MultilineArrayBraceLayout:
  Enabled: true

Layout/MultilineArrayLineBreaks:
  Enabled: true
  AllowMultilineFinalElement: true

Layout/MultilineBlockLayout:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true
  AllowMultilineFinalElement: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
  AllowMultilineFinalElement: true

Layout/MultilineMethodParameterLineBreaks:
  Enabled: true
  AllowMultilineFinalElement: true

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Lint/AmbiguousRange:
  Enabled: true

Lint/DisjunctiveAssignmentInConstructor:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Lint/HashCompareByIdentity:
  Enabled: true

Lint/HeredocMethodCallPosition:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/PercentStringArray:
  Enabled: true

Lint/RedundantCopEnableDirective:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/RedundantSafeNavigation:
  Enabled: true

Lint/ScriptPermission:
  Enabled: true

Lint/SendWithMixinArgument:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/SuppressedException:
  Enabled: true

Lint/SymbolConversion:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/ToJSON:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

# Replaced by Oyster/UnusedMethodArgument
Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Metrics/AbcSize:
  Enabled: true
  Max: 50

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 10

Metrics/BlockNesting:
  Enabled: true

Metrics/BlockLength:
  Enabled: true
  Max: 20
  AllowedMethods:
    - namespace
    - draw
    - configure
    - setup
    - guard
    - group
    - watch
    - task
    - create_table
    - resources

Metrics/ClassLength:
  Enabled: true
  Max: 300
  Exclude:
    - "app/graphql/types/company_type.rb"
    - "app/graphql/types/query_type.rb"

Metrics/MethodLength:
  Enabled: true
  Max: 25

Metrics/ModuleLength:
  Enabled: true
  Max: 300

Naming/AccessorMethodName:
  Enabled: true

Naming/AsciiIdentifiers:
  Enabled: true

Naming/BlockForwarding:
  Enabled: true

Naming/FileName:
  Enabled: true

Naming/HeredocDelimiterNaming:
  Enabled: true

Naming/MemoizedInstanceVariableName:
  Enabled: true

Naming/MethodName:
  Enabled: true

Naming/MethodParameterName:
  AllowedNames: as, at, by, db, id, in, io, ip, of, on, os, pp, to, cc
  Enabled: true

Naming/PredicateName:
  Enabled: true

Naming/VariableNumber:
  Enabled: true

Performance/DeletePrefix:
  Enabled: true

Performance/DeleteSuffix:
  Enabled: true

Performance/MethodObjectAsBlock:
  Enabled: true

Performance/RedundantEqualityComparisonBlock:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/Sum:
  Enabled: true

Performance/MapMethodChain:
  Enabled: false

RSpec/BeEq:
  Enabled: true

RSpec/BeNil:
  Enabled: true

RSpec/DescribedClassModuleWrapping:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

RSpec/ExcessiveDocstringSpacing:
  Enabled: true

RSpec/Focus:
  Enabled: true
  # Disable auto-correct so editors do not remove focus during development.
  AutoCorrect: false

RSpec/IdenticalEqualityAssertion:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/SubjectDeclaration:
  Enabled: true

RSpec/VerifiedDoubles:
  Enabled: false

Security/IoMethods:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Style/AccessModifierDeclarations:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/DateTime:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleCopDisableDirective:
  Enabled: true

Style/EvenOdd:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/FormatString:
  Enabled: true
  EnforcedStyle: percent

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/MapToHash:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/MinMax:
  Enabled: true

Style/MultilineInPatternThen:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Style/NegatedUnless:
  Enabled: true

Style/PercentQLiterals:
  Enabled: true

Style/RedundantCapitalW:
  Enabled: true

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/SignalException:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/StringMethods:
  Enabled: true

Style/SwapValues:
  Enabled: true

Style/SymbolProc:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/UnlessLogicalOperators:
  Enabled: true

Style/ZeroLengthPredicate:
  Enabled: true
